# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SoundCast' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SoundCast

  target 'SoundCastTests' do
    inherit! :search_paths
    pod 'AlamofireImage', '~> 3.3'
    pod 'Alamofire', '~> 4.7'
    # Pods for testing
  end

end
